### PR TITLE
[mobile_static] Use desktop aes on mobile_static.

### PR DESCRIPTION
**Pull request by alexanderkyte**

### CODE REVIEW

**Comment by alexanderkyte** [comment]
@spouliot , @marek-safar Is there any reason I shouldn't do this?

**Comment by marek-safar** [comment]
It looks like the guard should be `#if MONOTOUCH` instead

**Comment by alexanderkyte** [comment]
I don't know if Xammac behavior depends on this at all.

**Comment by marek-safar** [comment]
It does not, xammac is not full-aot

**Comment by spouliot** [comment]
lgtm

**Pull request merged**
